services:
  nginx:
    image: nginx:latest
    depends_on:
      - app
      - authentik
    #     condition: service_healthy 
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy_headers.conf:/etc/nginx/proxy_headers.conf:ro
      - ./nginx/ssl/:/etc/nginx/ssl
      - ./build/:/usr/share/nginx/html
    networks:
      - frontend
networks:
  frontend:
