from src.base.scheme import BaseCreateScheme, BaseResponseScheme


class LanguageCreateScheme(BaseCreateScheme): ...


class LanguageResponseScheme(LanguageCreateScheme, BaseResponseScheme): ...


class TextCreateScheme(BaseCreateScheme): ...


class TextResponseScheme(TextCreateScheme, BaseResponseScheme): ...


class TagCreateScheme(BaseCreateScheme): ...


class TagResponseScheme(TagCreateScheme, BaseResponseScheme): ...


class ActionCreateScheme(BaseCreateScheme): ...


class ActionResponseScheme(ActionCreateScheme, BaseResponseScheme): ...


class ReactCreateScheme(BaseCreateScheme): ...


class ReactResponseScheme(ReactCreateScheme, BaseResponseScheme): ...


class CommentCreateScheme(BaseCreateScheme): ...


class CommentResponseScheme(CommentCreateScheme, BaseResponseScheme): ...


class CategoryCreateScheme(BaseCreateScheme): ...


class CategoryResponseScheme(CategoryCreateScheme, BaseResponseScheme): ...
