from src.base.scheme import BaseCreateScheme, BaseResponseScheme


class ProjectCreateScheme(BaseCreateScheme): ...


class ProjectResponseScheme(ProjectCreateScheme, BaseResponseScheme): ...


class BaseDataCreateScheme(BaseCreateScheme): ...


class BaseDataResponseScheme(BaseDataCreateScheme, BaseResponseScheme): ...


class BoardCreateScheme(BaseCreateScheme): ...


class BoardResponseScheme(BoardCreateScheme, BaseResponseScheme): ...


class CheckListCreateScheme(BaseCreateScheme): ...


class CheckListResponseScheme(CheckListCreateScheme, BaseResponseScheme): ...


class ColumnCreateScheme(BaseCreateScheme): ...


class ColumnResponseScheme(ColumnCreateScheme, BaseResponseScheme): ...


class TaskCreateScheme(BaseCreateScheme): ...


class TaskResponseScheme(TaskCreateScheme, BaseResponseScheme): ...
